name: nest
description: "A new Flutter package project."
version: 0.1.0
repository: https://github.com/Atanu-Sabyasachi/nest
homepage: https://github.com/Atanu-Sabyasachi/nest
funding:
  - https://buymeacoffee.com/atanusabyasachi

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  uuid:
  encrypt:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: